# Generated by Django 4.1 on 2022-09-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='Fixing',
        ),
        migrations.AlterField(
            model_name='budget',
            name='Instalation',
            field=models.CharField(choices=[('Tipo de instalação', 'Tipo de instalação'), ('Manutenção', 'Manutenção'), ('Instalação Monosplit', 'Instalação Monosplit'), ('Instalação Multisplit', 'Instalação Multisplit')], max_length=128),
        ),
    ]
