# Generated by Django 4.1 on 2022-09-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_remove_budget_fixing_alter_budget_instalation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Division_1',
            field=models.CharField(choices=[('Selecionar Divisão', 'Selecionar Divisão'), ('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], default='Selecionar Divisão', max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_2',
            field=models.CharField(blank=True, choices=[('Selecionar Divisão', 'Selecionar Divisão'), ('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], default='Selecionar Divisão', max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_3',
            field=models.CharField(blank=True, choices=[('Selecionar Divisão', 'Selecionar Divisão'), ('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], default='Selecionar Divisão', max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_4',
            field=models.CharField(blank=True, choices=[('Selecionar Divisão', 'Selecionar Divisão'), ('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], default='Selecionar Divisão', max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_5',
            field=models.CharField(blank=True, choices=[('Selecionar Divisão', 'Selecionar Divisão'), ('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], default='Selecionar Divisão', max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_6',
            field=models.CharField(blank=True, choices=[('Selecionar Divisão', 'Selecionar Divisão'), ('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], default='Selecionar Divisão', max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='zip_code',
            field=models.CharField(default='1372-010', max_length=64),
        ),
    ]
