# Generated by Django 4.1 on 2022-09-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_alter_budget_division_1_alter_budget_division_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Division_1',
            field=models.CharField(choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_2',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_3',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_4',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_5',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_6',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Instalation',
            field=models.CharField(choices=[('Manutenção', 'Manutenção'), ('Instalação Monosplit', 'Instalação Monosplit'), ('Instalação Multisplit', 'Instalação Multisplit')], max_length=128, verbose_name='Tipo de instalação'),
        ),
    ]
