# Generated by Django 4.1 on 2022-10-30 10:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_alter_budget_area_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='user',
        ),
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_1',
            field=models.CharField(choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64, verbose_name='Divisão 1'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_2',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64, verbose_name='Divisão 2'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_3',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64, verbose_name='Divisão 3'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_4',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64, verbose_name='Divisão 4'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_5',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64, verbose_name='Divisão 5'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Division_6',
            field=models.CharField(blank=True, choices=[('Quarto', 'Quarto'), ('Sala', 'Sala'), ('Cozinha', 'Cozinha'), ('Garagem', 'Garagem'), ('Sotão', 'Sotão'), ('Outros', 'Outros')], max_length=64, verbose_name='Divisão 6'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='address',
            field=models.CharField(default='Rua e Localidade', max_length=128, verbose_name='Morada'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='budget',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='zip_code',
            field=models.CharField(default='1372-010', max_length=64, verbose_name='Código Postal'),
        ),
    ]
