# Generated by Django 4.1 on 2022-10-30 11:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_alter_budget_budget_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+351', max_length=128, region=None, verbose_name='Contacto'),
        ),
    ]
